services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    working_dir: /app
    container_name: thinklink-nginx
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
        - USER_NAME=${USER_NAME:-petr}
        - GROUP_NAME=${GROUP_NAME:-petr}
      context: ./docker/php
    working_dir: /app
    container_name: thinklink-app
    depends_on:
      - database
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
    container_name: thinklink-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    container_name: thinklink-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thinklink.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database
