services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thinklink.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database
volumes:
  postgres_data:
