# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Note: when changing the allowed mime types, also check tha allowed mime types in the App\Form\DTO\UploadFileFormData class (in the Assert section)
    # Source: https://www.iana.org/assignments/media-types/media-types.xhtml
    app.allowed_image_mime_types: ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml']
    app.allowed_pdf_mime_types: ['application/pdf']
    app.allowed_note_mime_types: ['text/plain', 'text/markdown']
    app.allowed_zip_mime_types: ['application/zip']
    app.allowed_mime_types: ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml', 'application/pdf', 'text/plain', 'text/markdown', 'application/zip']
    app.temp_upload_directory: '%kernel.project_dir%/var/temp'
    # Source of czech stop words: https://nlp.fi.muni.cz/cs/StopList
    app.stop_words_cz: ['a','v','se','na','je','že','o','s','z','do','i','to','k','ve','pro','za','by','ale','si','po','jako','podle','od','jsem','tak','jsou','které','který','jeho','však','bude','nebo','už','jen','byl','jak','u','co','při','až','aby','má','když','než','ze','která','před','být','také','bylo','jsme','není','jejich','ještě','ani','mezi','byla','své','roku','již','pak','první','roce','kteří','další','proti','let','tím','může','korun','řekl','tom','kde','či','tedy','pouze']

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Form\Validator\UploadedFileConstraintValidator:
        arguments:
            $allowedMimeTypes: '%app.allowed_mime_types%'

    App\Service\RelevantNotes\FeatureExtraction\TextPreprocessor:
        arguments:
            $stopWordsCz: '%app.stop_words_cz%'

    # Source: https://symfony.com/doc/current/service_container.html#service-parameters and https://symfony.com/doc/current/service_container.html#choose-a-specific-service
    # HOW TO ADD ANOTHER FILE HANDLER STRATEGY:
        # 1. Create a new class in the App\Service\FileHandler folder
        # 2. Implement the FileHandlerInterface
        # 3. Add the new class to the services.yaml right below this comment block
        # 4. Add the new class to the FileHandlerCollection arguments array (so it can be autowired)
        # 5. Consider adding the new upload directory to the parameters section in services.yaml file
        # 5. Now the new strategy will be automatically considered when the FileHandlerCollection is used
    App\Service\FileHandler\ImageFileStrategy:
        arguments:
            $allowedMimeTypes: '%app.allowed_image_mime_types%'

    App\Service\FileHandler\PdfFileStrategy:
        arguments:
            $allowedMimeTypes: '%app.allowed_pdf_mime_types%'

    App\Service\FileHandler\NoteFileStrategy:
        arguments:
            $allowedMimeTypes: '%app.allowed_note_mime_types%'

    # ZipArchiveStrategy is a special case - it is not included in the FileHandlerCollection because of the dependency loop
    App\Service\FileHandler\ZipArchiveStrategy:
        arguments:
            $allowedMimeTypes: '%app.allowed_zip_mime_types%'
            $uploadDirectory: '%app.temp_upload_directory%'

    App\Service\FileHandler\FileHandlerCollection:
        arguments:
            $fileHandlers:
                - '@App\Service\FileHandler\ImageFileStrategy'
                - '@App\Service\FileHandler\PdfFileStrategy'
                - '@App\Service\FileHandler\NoteFileStrategy'


    # Relevant notes strategies (https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services)
    App\Service\RelevantNotes\TitleMatchStrategy\PhraseTitleMatchStrategy:
        tags:
            - { name: 'app.strategy.title_match', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 2 }

    App\Service\RelevantNotes\TitleMatchStrategy\PlainCoverDensityTitleMatchStrategy:
        tags:
            - { name: 'app.strategy.title_match', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 0 }

    App\Service\RelevantNotes\TitleMatchStrategy\PlainTitleMatchStrategy:
        tags:
            - { name: 'app.strategy.title_match', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 4 }

    App\Service\RelevantNotes\TitleMatchStrategy\WebsearchTitleMatchStrategy:
        tags:
            - { name: 'app.strategy.title_match', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 3 }

    App\Service\RelevantNotes\TitleMatchStrategy\TsqueryORTitleMatchStrategy:
        tags:
            - { name: 'app.strategy.title_match', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 4 }

    App\Service\RelevantNotes\TfIdfMatrixStrategy\CosineDistanceTfIdfMatrixStrategy:
        tags:
            - { name: 'app.strategy.tf_idf', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 8 }

    App\Service\RelevantNotes\VectorEmbeddingStrategy\OpenAIVectorEmbeddingStrategy:
        tags:
            - { name: 'app.strategy.vector_embedding', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 9 }

    App\Service\RelevantNotes\VectorEmbeddingStrategy\GeminiVectorEmbeddingStrategy:
        tags:
            - { name: 'app.strategy.vector_embedding', priority: 1 }
            - { name: 'app.relevant_notes_strategy', priority: 10 }

    App\Controller\NoteController:
        arguments:
            - !tagged_iterator { tag: app.relevant_notes_strategy, exclude: ['App\Service\RelevantNotes\TitleMatchStrategy\PhraseTitleMatchStrategy','App\Service\RelevantNotes\TitleMatchStrategy\PlainTitleMatchStrategy','App\Service\RelevantNotes\TitleMatchStrategy\WebsearchTitleMatchStrategy','App\Service\RelevantNotes\VectorEmbeddingStrategy\OpenAIVectorEmbeddingStrategy','App\Service\RelevantNotes\TitleMatchStrategy\PlainCoverDensityTitleMatchStrategy'] }

    App\Message\GetVectorEmbeddingMessageHandler:
        arguments:
            - !tagged_iterator { tag: app.strategy.vector_embedding, exclude: ['App\Service\RelevantNotes\VectorEmbeddingStrategy\OpenAIVectorEmbeddingStrategy']}